# Generated by Django 5.2 on 2025-05-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_image",
                    models.FileField(blank=True, default=None, upload_to=""),
                ),
                ("member_name", models.CharField(max_length=50)),
                ("member_position", models.CharField(max_length=50)),
            ],
        ),
    ]
