# Generated by Django 5.2 on 2025-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="member_image",
            field=models.ImageField(upload_to="members/"),
        ),
    ]
