# Generated by Django 5.2 on 2025-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_teammember_member_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_image", models.ImageField(upload_to="foods/")),
                ("food_name", models.CharField(max_length=50)),
                ("food_des", models.CharField(max_length=100)),
            ],
        ),
    ]
