# Generated by Django 5.2 on 2025-05-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_contactformenquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="food_des",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="food_name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("upi", "UPI"),
                            ("card", "Credit/Debit Card"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.fooditem"
                    ),
                ),
            ],
        ),
    ]
