# Generated by Django 5.2 on 2025-06-07 11:31

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_title", models.CharField(max_length=75)),
                ("news_icon", models.CharField(blank=True, max_length=20, null=True)),
                ("news_desc", tinymce.models.HTMLField()),
                (
                    "news_slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="news_title",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
