# Generated by Django 5.2 on 2025-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_icon",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
