# Generated by Django 5.2 on 2025-05-14 09:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_news_news_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from=models.CharField(max_length=75),
                unique=True,
            ),
        ),
    ]
